export enum ColorName {
  Blue = 'blue',
  BlueDark = 'blue-dark',
  BlueDarker = 'blue-darker',
  BlueLight = 'blue-light',
  BlueGrey = 'blue-grey',
  BlueLighter = 'blue-lighter',
  Red = 'red',
  RedLight = 'red-light',
  RedDark = 'red-dark',
  White = 'white',
  Grey = 'grey',
  GreyDark = 'grey-dark',
  GreyLight = 'grey-light',
  GreyLighter = 'grey-lighter',
}

export const COLORS = {
  [ColorName.Blue]: '#2079BF',
  [ColorName.BlueLight]: '#4DA2D3',
  [ColorName.BlueLighter]: '#8ad4fc',
  [ColorName.BlueDark]: '#0D4369',
  [ColorName.BlueDarker]: '#063249',
  [ColorName.BlueGrey]: '#527C97',
  [ColorName.Red]: '#E3342F',
  [ColorName.RedLight]: '#ed7876',
  [ColorName.RedDark]: '#bf1715',
  [ColorName.White]: '#FFFFFF',
  [ColorName.Grey]: '#9babb4',
  [ColorName.GreyLight]: '#E5E7EB',
  [ColorName.GreyLighter]: '#F3F4F6',
  [ColorName.GreyDark]: '#4B5563',
};
